---
name: Lint and Test

on:
  push:
    branches: ["main"]
    paths:
      - "api/*"
  pull_request:
    branches: ["main"]
    paths:
      - "api/*"

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: "1.23"
  #
  #     - name: Build
  #       working-directory: ./api
  #       run: go build -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        working-directory: ./api
        with:
          version: v1.60

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Test
        working-directory: ./api
        run: go test -v ./...
